name: grpc_server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.5 <3.0.0'

# dependencies:
#   path: ^1.8.0q

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  path: ^1.7.0
  grpc: ^2.1.3
  protobuf: ^1.0.1
